### ISSUE TITLE
Adjust Workflow for Journal Publication

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#480]
Based on conversation in #474 

### Acceptance Criteria

- [x] Given I am a lead author on an ATBD, when I visit my ATBD that is in an In Review status, then I have the option to "Make Public Request" that is sent to the Curator
- [x] Given I am a curator who has received a Make Public Request, when I accept that request then the ATBD moves into a Public status, which is the final status for a document
- [x] All Journal Details radio buttons (Not to be published, To be Published, Submitted, Published) are available to be selected at all times of the document workflow
- [x] Update WorkFlow overview diagram that pops up upon ATBD creation to match new workflow and verbiage
- [x] Update text on modal that appears upon save based on below

## Modal Text
Header
Update Minor Version?

Negative button text
No, don't update yet

Affirmative. button text
Yes, update version

### Confirmation modal after clicking Yes, update version
Header
Are you sure?

Affirmative button text
Confirm

**Comment by aboydnw** [comment]
@deborahUAH reposting the relevant questions to this ticket: 

1. Who would be the one to close out the Open Review and mark an ATBD as Complete? The Curator? Reviewer? Lead Author?
2. On the Curator dashboard, should we add "Complete" as a stage & metric?
3. On the Contributor dashboard, should we split the Public tab into Completed & Published?

**Comment by danielfdsilva** [comment]
The current flow assumes that the documents go through a curation process to be published within the tool. Whether or not a document is published to a journal is additional to this process. Currently if a document is sent to the journal, there is an icon next to the status

![image](https://user-images.githubusercontent.com/1090606/157837726-b1bc7b2e-41b0-4d6e-8e9b-0d18cd3264b5.png)

Maybe changing the language here could help with the distinction since the icon can be missed

**Comment by aboydnw** [comment]
@danielfdsilva I'm reading back through this ticket and trying to figure out how and where the icon appears that you mentioned above. How does a user "publish to a journal" and then where does the icon appear?

**Comment by danielfdsilva** [comment]
@aboydnw Publishing to a journal is not done through APT.
This information is meta. A user can say that the document was published to a journal, but the actual publishing is done outside of APT.

In the Closeout step you can select that the document will be published to a journal. This will enable an additional form to be filled (appearing after you select "To be published").
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1090606/179189790-f3c5bc53-6a5c-4947-900e-27e252a95774.png">

Since this is meta information, this is meant to be updated as the document moves along the publication workflow.
You will notice that while a document is NOT in "publication" you can't change the journal state.
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1090606/179190051-8ae64966-4c35-4051-b389-cfaf78029681.png">


Once the document is in publication (or even published) you can come back and change this value and will make the icon show. This icon will be visible in the status pill (top left when viewing a document) and also in the "Document status modal" which shows up when you press the status pill.

The icon is also different depending on the selected state.
| Submitted | Published |
|--|--|
| <img width="378" alt="image" src="https://user-images.githubusercontent.com/1090606/179190691-9284c318-5f2f-4066-a31d-6f91b9403d2e.png"> | <img width="379" alt="image" src="https://user-images.githubusercontent.com/1090606/179190610-bdc28245-0f29-4eeb-b14f-4aa1537ed970.png"> |

Note that this icon only shows up when the document is published. While in draft or another state it won't be displayed since the document is not yet published to a journal.

Let me know if there's any other part that needs clarification.

**Comment by aboydnw** [comment]
Thanks @danielfdsilva that is really helpful. I am now thinking we can probably just change some of the verbiage so we don't have "publish" meaning two different things (published to APT and published to a journal)

Another question for context before we start making changes, do you know the backstory behind the "In Publication" step? Is there a reason we have this intermediary step as opposed to going straight from In Review to Published? 
The explanation on the site makes it sound like users should put the ATBD in the In Publication stage if it is meant to go to a journal, but the 4 radio buttons and different icons you showed above seem to serve a similar purpose.

**Comment by danielfdsilva** [comment]
@aboydnw The "In publication" stage is where things related to journal publication happen and where for example you get the DOI. After this you publish the document making it available.

We created these statuses based on a [workflow that was shared with us](https://www.figma.com/file/pkOENjghb2Lq08DUGDYjVG/ATBDs-(answered)?node-id=0%3A1), over which we iterated.

**Comment by aboydnw** [comment]
Thanks @danielfdsilva this is super helpful! 

@deborahUAH @oliverroick @naomatheus let's chat about this ticket and workflow when you get back. I think we may be able to reduce the complexity of the solution here by fitting within the existing functionality and changing some of the verbiage.

**Comment by aboydnw** [comment]
Summing up the convo today, we should have some further discussion @oliverroick @naomatheus 

In general, we can move forward with the proposal to NOT add a completed workflow step, focusing on using the Journal Details outlined above. This would mean a few changes:
1. Updating "Published" status to be a different word (Public, Completed, Available in APT, etc)
2. Removing the "In Publication" status
3. Updating the workflow from In Review to Completed to match new verbiage
4. Updating radio buttons of Journal details to more closely match the user workflow. Potentially moving Submitted and Published options to be actions from the ATBD view page/dashboard view that can be completed by the lead author or Curator
5. Journal PDF is only available if PDF is to be published

**Comment by naomatheus** [comment]
[Issue header](https://github.com/NASA-IMPACT/nasa-apt/issues/480) takes precedent over the comments below

Booked a time to chat with @aboydnw on Monday 8/8

Does this seem accurate of 1 - 5 that Anthony laid out in the comment above this one @oliverroick? 
Anticipating what specifically needs to be updated and open questions.

1. Updating "Published" status to be a different word (Public, Completed, Available in APT, etc)
- Which term exactly?
- FE (frontend) change.

2. Removing the "In Publication" status
- FE and BE (backend) change
- - Edit permissions model
- - Look into DB model constraints
- - Remove the need for Curator to approve a publication request
- - Currently: The only way out of In Review is to request Publication
- - Change the `request publication` button to "Make Public Request"
- - We need a function to go from In Review to Public
- - An action for the lead author to move a document from In Review to Public

3. Updating the workflow from In Review to Public to match new verbiage
- FE and BE change

4. Updating radio buttons of Journal details to more closely match the user workflow. Potentially moving Submitted and Published options to be actions from the ATBD view page/dashboard view that can be completed by the lead author or Curator
- See Issue header above
- Backend, this involves checking backend permissions model to allow any Journal Details button to select its corresponding status regardless of the document's current status

5. Change the "Continue Editing" button in document save pop-up to "Save Without Updating Minor Version"

**Comment by aboydnw** [comment]
I get the same server error when trying to step through the workflow as what I was getting on #527 :( 

Also, in staging I still see this modal describing the old workflow. 
![image](https://user-images.githubusercontent.com/92742765/186238680-97a50a4c-5ae6-492f-a3b3-6c421de86c82.png)

**Comment by oliverroick** [comment]
@aboydnw This may have been because a deployment failed previously, which was supposed to update the modal. It looks fine locally, and we're working to get an update pushed to staging soon.

**Comment by bwbaker1** [comment]
@aboydnw @wrynearson 

This issue is a little confusing given the header and conversation above, but I'm assuming the end game is [this](https://github.com/NASA-IMPACT/nasa-apt/issues/480#issuecomment-1206646038).  If so, I am a little confused on 5 - Change the "Continue Editing" button in document save pop-up to "Save Without Updating Minor Version".  I am not seeing this change, but I may be looking in the wrong location.  When and where would this new text appear?

Otherwise, I think we can call this complete.

**Comment by oliverroick** [comment]
> This issue is a little confusing given the header and conversation above, but I'm assuming the end game is https://github.com/NASA-IMPACT/nasa-apt/issues/480#issuecomment-1206646038. If so, I am a little confused on 5 - Change the "Continue Editing" button in document save pop-up to "Save Without Updating Minor Version". I am not seeing this change, but I may be looking in the wrong location. When and where would this new text appear?

@aboydnw @naomatheus I wasn't part of this conversation and I don't know what this refers to. Can you clarify where this change should happen?

**Comment by aboydnw** [comment]
@oliverroick this is in regards to the last AC: "Update text on modal that appears upon save based on below"
Which is a little vague, probably because we wrote it live on a call so didn't think about being more explicit, my fault.

When an author edits a published document and clicks Save, they get prompted to bump the minor version. Right now, that modal is a little confusing, so we wanted to clear up the language a bit. Basically, we wanted people to be able to edit and save a published document without having to bump the minor version. But, if they wanted to bump the minor version, to give them that option. I believe all of this functionality exists today, the wording of the modal that appears when you click save just doesn't make it super clear. (side note, this modal only appears if you are editing a published document. it does not appear if you are editing a draft.)
So, that's where the modal text in the top description came from. Essentially, we are picturing two modals. One that appears first after clicking save to ask if they want to bump the minor version, and a confirmation modal if they click Yes. Pasting below as well.

Modal Text
Header
Update Minor Version?

Negative button text
No, don't update yet

Affirmative. button text
Yes, update version

Confirmation modal after clicking Yes, update version
Header
Are you sure?

Affirmative button text
Confirm

**Comment by oliverroick** [comment]
@aboydnw I've made the change according to the AC.

The first popup looks like this:

<img width="527" alt="Screenshot 2022-09-16 at 15 27 20" src="https://user-images.githubusercontent.com/159510/190563510-77000b1e-38cd-41aa-88cb-7143bf953768.png">

and the second like this:

<img width="526" alt="Screenshot 2022-09-16 at 15 27 29" src="https://user-images.githubusercontent.com/159510/190563534-b51f6756-cb0b-402f-abf1-72b8c9e90774.png">

What I'm confused about is this statement: 

> Change the "Continue Editing" button in document save pop-up to "Save Without Updating Minor Version"

I'm assuming we want the button that reads "No, don't update yet" to "Save Without Updating Minor Version". Is that correct? I can make the change but it breaks the layout because the text is too long. 

<img width="530" alt="Screenshot 2022-09-16 at 15 34 09" src="https://user-images.githubusercontent.com/159510/190563994-cfe3fbad-e1d4-42bc-8a7d-ab64db4b1d34.png">

**Comment by aboydnw** [comment]
Oh, no sorry I didn't catch that was the confusion 😅 
@bwbaker1 the text you are looking for is outdated content. We refined the content to be what is in the top level description.
So, @oliverroick it looks like you have it correct. No changes needed.
Apologies for the confusion here.

**Comment by bwbaker1** [comment]
@aboydnw @wrynearson @oliverroick @deborahUAH I tested the publication workflow.  Most of this seems correct other than a little text wording.

(1) After an author makes all of the changes after review and wants to request the ATBD to be made public, the tab should be worded as "Make public request." It currently is worded as "Request publication."


![Image](https://user-images.githubusercontent.com/56319064/197029692-20fe9169-c4e7-41ae-832e-e41d259368b6.jpeg)

(2) Similar to the point above, when a curator gets a make public request, the tab should say "Make public." It is currently worded as "Publish." 


![Image](https://user-images.githubusercontent.com/56319064/197032102-12b2ccaf-0bd8-4231-8f42-de5916ecaf6f.jpeg)


Other than this changes in wording, everything else regarding this ticket looks correct - journal details radio buttons are correct; text pop-ups are correct when an author makes a minor update; and the workflow diagram that appears when a user creates a new ATBD is also correct.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. Same question as on [500](https://github.com/NASA-IMPACT/nasa-apt/issues/500#issuecomment-1290754498) – do you and @deborahUAH agree to push our current implementation of this ticket from staging to production? We will then address these text changes at a later date. It may be more complex than just simple text changes which would require checking text in other locations (i.e., the status tracker modal).

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH Again, my opinion is this could be pushed as well since it just needs a little tweak in wording.

**Comment by bwbaker1** [comment]
@wrynearson I talked to Deborah and she gave the go ahead to push this ticket.

**Comment by wrynearson** [comment]
Thanks @bwbaker1.

For future discussion related to your comments, I think we would need to adjust the wording in:
1. The new document popup
<img width="763" alt="Screenshot 2022-10-26 at 12 06 56" src="https://user-images.githubusercontent.com/25919630/197998957-975e6404-17d5-4687-a74e-ab2d35c4ce78.png">
2. The dashboard status filter dropdown
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/25919630/197999187-57606ff2-7f1c-4b88-b8fc-fb3ca9140431.png">
3. The popup window for both points above
<img width="537" alt="image" src="https://user-images.githubusercontent.com/25919630/197999572-b3386101-a1ae-425e-a93d-12b8f15ae912.png">
4. Toast (green/red popups in the bottom right) text


If you could consider the other text that would need to be updated (or if it should be), that would help us implement this request.
