### ISSUE TITLE
Allow input of inline Latex equations

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#502]
### Description

Second ticket from #494 that will enable inline equations within the rich text editor. This includes the option for users to define an equation as either a block equation or an inline equation within the equation add/edit modal.

### Acceptance Criteria
1. When adding or editing an equation, there is an option for a user to define the equation as inline or block
2. If the equation being added is an inline equation, then the equation appears within the text of the surrounding paragraph, following styling decided with Ricardo
3. I can edit an inline equation, and can change it to become a block equation, and vice versa

**Comment by danielfdsilva** [comment]
Wireframes for reference: https://www.figma.com/proto/983kpjf1sXyt2CmKKKXhjY/Wireframes?page-id=1369%3A5004&node-id=1371%3A5065&viewport=487%2C449%2C0.19&scaling=min-zoom

**Comment by leothomas** [comment]
@danielfdsilva was there ever a conclusion on how to address the problem of the document processing each section as a separate item (ie: if a document section looks like: `[{text}, {equation}, {text}]` that should show up in the document as: 
```text
text

equation

text
```

Since that's true of all sections (so far) we process each section item one at a time, inserting a newline (`\n`) between each section item. However, for an inline equation to be stored in the database as `[{text}, {inline-equation}, {text}]` and then displayed as
```text
text inline-equation text
```

The document process has to have knowledge about both the preceding _and_ proceeding sections to properly handle an inline equation, for example in the case of an inline equation being in between a table or image image and text section. eg: 
`[{text}, {inline-equation}, {image}]`
should be generated in the PDF as: 
```text
text inline-equation

image
```
and `[{list}, {inline-equation}, {text}]` should be handled as: 
```text
list

inline-equation text
```

**Comment by leothomas** [comment]
Eg: here's what an inline equation looks like added to the end of the `abstract`: 
<img width="485" alt="image" src="https://user-images.githubusercontent.com/11858457/170580328-64d82aee-d068-4fde-975d-5dc1481f8e92.png">

It's placed on a separate line because each "child" element of a high-level section (such as the `abstract`) gets separated by a newline (`\n`)

**Comment by oliverroick** [comment]
As I said in the comment in the other PR, I don't think inline equations should ever on the same level as block elements. Inline equations should behave like other inline markup, like bold text, so they must be a child of a paragraph-like element. 

To use your examples, the structure that is produced when adding an inline equation is:

```
paragraph
  text
  inline-equation
image
```
and

```
list
  list-item
    text
  list-item
    text
paragraph
  text
  inline-equation
```

Consequently, in your abstract example, the structure is

```
paragraph
  text
paragraph
  inline-equation
```

and the PDF output in the first image is correct. 

The second image would be correct if the the abstract is marked up as:

```
paragraph
  text
  inline-equation 
```

I think it's down to the user editing the document to make sure inline equations end up where they should be.

**Comment by danielfdsilva** [comment]
@oliverroick Your logic is correct. The slate document model complicates things a little as there is a difference between a text node and a block node, which is where @leothomas' worries come into play.

A text node is a simple:
```json
{
  "text": "some text"
}
```

Whereas a block node:
```json
{
  "type": "equation",
  "children": [
    {
      "text": "latex~example: e=mc^2"
    }
  ]
}
```

The equation is treated as a block and therefore rendered as such. Leo explained it brilliantly in an issue (https://github.com/NASA-IMPACT/nasa-apt/issues/431).

Block level items are currently not allowed inside a paragraph, as things like equations, table, heading, etc, are inserted at root level. The solution, as Oliver is saying, is to ensure that the equation is added as a child of the paragraph (only when inline). We'll need to add some normalizers to slate to ensure that the structure is sound as the user can toggle between block and inline equations.

But the resulting document could look something like:
```json
{
  "children": [
    {
      "type": "p",
      "children": [
        {
          "text": "This is some "
        },
        {
          "text": "content",
          "bold": true
        },
        {
          "text": ". Then comes an equation."
        },
        {
          "type": "equation",
          "inline": true,
          "children": [
            {
              "text": "latex~example: e=mc^2"
            }
          ]
        }
      ]
    }
  ]
}
```
