### ISSUE TITLE
Version change log

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#527]
## Description
As a scientist interested in a specific ATBD, I want to view the version history of an ATBD so that I can better understand why the ATBD version was changed and what updates I might be missing by using an old version.
As a contributing author to an ATBD, I want to view the version history of an ATBD so that I can investigate what changes have recently been made.

Currently, users have to click the Download button in the top to access PDFs from previous versions. 

![Image](https://user-images.githubusercontent.com/92742765/179059460-3f2687e7-8d7c-4892-a618-41fe0dae203e.png)

This is both a) not very user friendly when there are more than a few versions for an ATBD and b) does not provide the version description information if a user wants to know why a minor or major version was created. 

The version description is currently a field on every ATBD that I believe is not being used, but is still being stored?

![Image](https://user-images.githubusercontent.com/92742765/179061280-0a77e80c-d19c-4bbb-8fa7-d636d5a6ffab.png)

## Acceptance Criteria

- [ ] Given I am a user in APT, when I view an ATBD then I see an option to view the "Change Log" of that ATBD (flexible on where this lives)
- [ ] Given I am viewing a public ATBD, when I select to view the "Change Log" then I see a list of all previous versions, their version descriptions, and their associated PDFs (flexible on how this appears, new page, modal, section, etc.)
- [ ] Given I am a user in APT, when I view an ATBD then I no longer see a download button in the top right of the screen (to be replaced by the Change Log functionality)

**Comment by aboydnw** [comment]
@oliverroick @naomatheus @wrynearson Woot woot! exciting feature. A few questions/feedback, now that we are able to see this:

1. I think a "Download PDF" button is still valuable. It is a pretty key action. Doesn't necessarily have to exist as it used to, but right now there is no option to Download PDF that isn't buried in the View changelog action. I would say downloading the pdf is on the same level as viewing the changelog, if not even more important! For public users, it is probably the most important action to take when viewing an ATBD (besides basic nav actions). I wonder if we should keep the button and just show the most recent/current version pdf? Then they access the changelog for more? Or maybe the action for viewing changelog says "Download "PDF(s)" or something like that? I think there are trade-offs to both.
2. Should the changelog show PDFs for all minor versions? I just did a smoke test on one of my old ATBDs with multiple minor versions and it only showed the current version. Is this related to the document search issues? If so, ignore.
3. I tried creating a new doc in case the lack of versions above was due to document search issues. Everytime I click the save button (whether I am creating a new doc or updating an existing one) I get to this error page. When I click back to go to the ATBD view page, the changes have in fact been saved. But I am not able to update the minor version. Is this perhaps related to this ticket? 

### Screenshot for #2 
![image](https://user-images.githubusercontent.com/92742765/186238209-b6ce0ec1-1001-4ad9-8146-e0b4e927b732.png)


### Screenshot for #3 
![image](https://user-images.githubusercontent.com/92742765/186238112-dfe00d7f-3be9-4414-9467-30e6f3fe1666.png)

**Comment by oliverroick** [comment]
> Should the changelog show PDFs for all minor versions? I just did a smoke test on one of my old ATBDs with multiple minor versions and it only showed the current version. Is this related to the document search issues? If so, ignore.

I don't think it is related to. I'm rendering all versions that are in the state for the current ATBD. It looks like it only includes the latest minor version.

@leothomas / @danielfdsilva do you have any background information in this. Are we only returning the latest minor version from the API? Is there a reason for this?

**Comment by danielfdsilva** [comment]
@oliverroick I'm not sure I understand the question. The api does not return info on the pdf and minor versions don't really exist (not like major ones that can actually be viewed).
When you create a "minor version" a pdf is created and stored and you can access it through a predicable link.

The download menu is using [a loop](https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/0d03609196d2ec9995660f72ce241a29c2080cb3/app/assets/scripts/components/documents/document-download-menu.js#L50-L58) to generate all the links.

Does this help?

**Comment by oliverroick** [comment]
@danielfdsilva 

I've created a modal that should list all versions of a document by looping over [`atbd.versions`](https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/0d03609196d2ec9995660f72ce241a29c2080cb3/app/assets/scripts/components/documents/document-changelog-modal.js#L36).

The result looks like this:

<img width="1022" alt="Screenshot 2022-08-31 at 18 35 27" src="https://user-images.githubusercontent.com/159510/187635774-2180df73-8e3d-41ca-83b4-bfdc61e430b8.png">

It includes v1.1 and v2.0, but we would expect it shows v1.0, v1.1, and v2.0. The API returns only v1.1 and v2.0 – why is v1.0 not included in the `versions` array when querying the ATDB?

**Comment by danielfdsilva** [comment]
That happens because v1.0 no longer exists.
Major versions are a thing. Whenever you create a new one the data is copied and you are left with 2 entries.
Minor versions are "faked". It is basically the "minor" field that gets incremented. You can't go back. You're still looking at the` v1.0`, but the "minor" is now `1`.

I was trying to find the document that was sent when this approach was agreed on, but can't find it. However I did find the section I was looking for. Some implementation details may now differ.

----


## Versioning

Keeping track of Minor Versions results in having a version tree to maintain (where for example version 1 and version 2 could continuously go on into minor 1.1, 1.2 / 2.1). The application would have to track different draft states and multiple ongoing review processes. This has big implications in data architecture, user experience, and interface.

Because of the the challenges listed above it was decided not to keep track of minor versions, but only of major with the following approach:

1. The ATBD starts at version 1 on a draft state
2. The ATBD is published and is now formally at version 1. At this time, a DOI can be generated and added to the ATBD.
3. Changes to version 1 are still allowed but should be minimal according to your internal guides. These changes can be made straight, and won’t have to go through a formal review process (see point on discussions). The ATBD major version and DOI do not change.
4. For greater transparency, users may log changes to the ATBD by indicating a minor version number and description of the changes. This is not enforced by the application.
5. Once a Major Version is in published state, the user can create a new Major Version from it. (v1 → v2-draft). Previous versions will remain editable.

Some implications and assumptions of this approach:

- a link to an ATBD version will always show the latest state. If there are multiple major versions (v1, v2) users can switch between these.
- it is only possible to have 1 major version in draft state. It’s not possible to be simultaneously working on v2-draft and v3-draft.
- a change in Major Version will go hand in hand with a change in the product version of a DOI
- When a new Major Version is created the DOI field is emptied.

### Minor versions:
Despite not storing minor versions, the user will have the ability to track what minor version the ATBD is in. This tacking is just informative and it will not be possible to go back to other minor versions. 
This minor version may be thought of as a field in the ATBD and the reason for this minor version to exist is to let users who have downloaded previous versions of the ATBD pdf know that minor edits were made. This “field” will be auto-incremented with the push of a button.

Since there’s no publishing workflow the user will have to bump the minor version themselves. To remind the user that this is a necessity, when the user is saving a published document, a prompt will be displayed somewhere along the lines:

> Are you done editing? If so consider bumping the version.

The user can then save the current view and continue the edition, or be taken to where the minor version can be bumped.
When the user is bumping the minor version the user will be able to edit the current version’s changelog.

### Minor versions and PDF
Because there’s no versioning workflow for minor versions (to avoid keeping version trees and concurrent editorial workflows), but it is still valuable to view past pdfs, everytime there’s a minor version bump a pdf will be generated and stored. These pdf are the only way to see what happened in minor versions.
The pdfs for previous minor version are selectable through the download dropdown.
PDFs will reflect the state of a document when the new minor version is created. Any minor changes will be visible in the interface but not on the PDF until the minor version is bumped.

**Example:**
v1.0 is created and user makes a change in a field. This change is not available in the v1.0.pdf. It will only be available once the user bumps the minor to v1.1. This is so to avoid a situation where the pdf of v1.0 is the same of v1.1 and is not possible to see any difference.

```
    Version: 1.2
     -- Bump version
    Version: 1.3 <-- this version is cached
     -- Edit 1
     -- Edit 2
     -- GET PDF for version 1.3 <-- this does not contain Edit 1 and Edit 2
     -- Bump version
    Version: 1.4 <-- this version now contains Edit 1 and Edit 2
```

On one hand, it is understandable why someone would want to see their edits before bumping the version. On the other hand, minor version bumps are supposed to be for small typo-like changes. If a change is complex enough that the pdf needs to be reviewed before bumping the version, that change probably warrants a new major version.

----

If you want to chat about this let me know

**Comment by oliverroick** [comment]
@danielfdsilva Thanks for the explanation, that helps.

**Comment by oliverroick** [comment]
@aboydnw Based on the above, the only thing we can do is to list out all of the major versions and their version descriptions and provide an option to download PDFs of any associated minor versions

**Comment by aboydnw** [comment]
@oliverroick we at least need the ability to download the PDFs. I think IMPACT is aware that they won't be able to pull up and edit old minor versions, so no worries there. The version description would be awesome to provide for previous minor versions somehow. If not, we can start with just PDFs and see how it goes.

**Comment by oliverroick** [comment]
@aboydnw The version descriptions of previous minor versions are not available, we only have the latest minor version and its version description in the database. 

The closest I can to this is:

<img width="1017" alt="Screenshot 2022-09-02 at 11 12 14" src="https://user-images.githubusercontent.com/159510/188038291-acf1c557-1453-4c2f-8141-7b4dec829f4b.png">

**Comment by aboydnw** [comment]
@oliverroick What changes would we have to put in place to be able to store the version description for the future? Not saying we need to store the entire document version, just the description. Even if we don't do that work as part of this ticket, would be good to know for any potential future work.

Also, looking at the UI you posted above, does that solve one of the original reasons we wanted to do a change log? Namely, that download dropdown could get exceedingly long and less usable as more minor versions are added. I think this is a step in the right direction, but if there are any other ways we could make this change log easier for people to see previous versions (even if it's only a PDF) then it might make this feature more impactful.

**Comment by oliverroick** [comment]
@aboydnw

> What changes would we have to put in place to be able to store the version description for the future? Not saying we need to store the entire document version, just the description. Even if we don't do that work as part of this ticket, would be good to know for any potential future work.

Regarding the complexity of this, I refer to [Daniel's comment](https://github.com/NASA-IMPACT/nasa-apt/issues/527#issuecomment-1232679033):

> Keeping track of Minor Versions results in having a version tree to maintain (where for example version 1 and version 2 could continuously go on into minor 1.1, 1.2 / 2.1). The application would have to track different draft states and multiple ongoing review processes. This has big implications in data architecture, user experience, and interface.
> 
> Because of the the challenges listed above it was decided not to keep track of minor versions

Implementing a change would be a new feature that needs to be properly spec'ed out. It will take several sprint for sure, but I can't give you a more precise estimate because I have no information. 

---

> Also, looking at the UI you posted above, does that solve one of the original reasons we wanted to do a change log? Namely, that download dropdown could get exceedingly long and less usable as more minor versions are added. I think this is a step in the right direction, but if there are any other ways we could make this change log easier for people to see previous versions (even if it's only a PDF) then it might make this feature more impactful.

If you have suggestions how to present this in a different way, feel free to share them in a new ticket that we can tackle in the future. I've been over three iterations of this ticket now, I consider this done.

**Comment by danielfdsilva** [comment]
@aboydnw @oliverroick Just for completion, we had kind of a changelog support.

It worked as follows:
```
Changelog:
Each major version will have a dedicated changelog. In this changelog it will be tracked what changed in relation to the previous major version (except in version 1 where there’s not previous), but also the changes for the current minor versions.
The workflow is something like:

1. Create new ATBD. It’s draft v1
2. Publish ATBD v1 (no changelog prompt because is v1)
3. Bump to v1.1 (Possible to edit changelog of v1 and list changes)
4. Created v2. It’s draft v2 (changelog of v2 is empty)
5. Publish ATBD v2 (changelog prompt - what changed in relation to v1)
6. Process repeats for other major and minor versions.
```

Instead of being a field in the ATBD, this was prompted when the version changed, however we were asked to remove it in favor or a field in the document itself.

**Comment by bwbaker1** [comment]
@oliverroick @aboydnw @wrynearson @deborahUAH 
I've tested the change log feature and have a few comments.  Hopefully, this isn't too confusing.

1) The major issue that I see is that version descriptions are not being rendered for older major versions.  Example - I create version 1.0 and as expected there is no descriptions in the change log.  Then update minor version to v1.1 and add a description in the version description field.


![Image](https://user-images.githubusercontent.com/56319064/190009488-78e64526-e1f5-4dc6-9c52-a412d142f3ff.jpeg)


And I see this in the change log:



![Image](https://user-images.githubusercontent.com/56319064/190009530-d4df1e87-1265-4682-963c-f7841baff2fd.jpeg)


Then I update to a new major version (v2.0) and add a description in the version description field. 
Because this is a new version of the document, the version description field is empty when I go into editing mode. 



![Image](https://user-images.githubusercontent.com/56319064/190009829-b80316fb-3a03-43ac-b5b7-bf1085401bc6.jpeg)


After publishing, here is my new change log.  Notice that major version 1 no longer has any descriptions.


![Image](https://user-images.githubusercontent.com/56319064/190009747-1744e510-4e00-4b94-b901-94ede5ab1a24.jpeg)


Same goes if I were to go through this process and create major version 3.0.  



![Image](https://user-images.githubusercontent.com/56319064/190010031-08e4e277-ccfd-4f86-9db7-b5744613ac5d.jpeg)


This is the big issue that I found.  Everything below is relatively minor.


2) After reading the conversation above, I think the current state of the tool only allowing users to download the current PDF of each major version is desirable. For example, if there is v2.1, v2.2, and v2.3, only v2.3 is available.  These are just minor updates by our definition.  What is important is that all changes for each minor version update are documented on the change log.  From the MSFC side, I think we need to re-evaluate the helper text and explain the version description field better.  

3) Similarly, it needs to be communicated to authors that nothing should be deleted from the version description field between minor updates (also needs MSFC discussion).  For example, if ATBD is being updated from v3.1 to v3.2, nothing can be deleted from the version description field from the previous update.  If it is deleted, than only the descriptions for the v3.2 update will be displayed in the change log.  I think this is okay as long as we communicate this well and maybe even inform authors to separate descriptions from each update (see image below; "Version 3.1 Update" and "Version 3.2 Update). 



![Image](https://user-images.githubusercontent.com/56319064/190007844-78a19836-f743-4711-8f26-9d06c620bb84.jpeg)

4) When I update a minor version, I get an error message when I try to save the version description field (see below).  However, it appears that it is saving the new content.  Content is still there if I exit editing mode and then restart editing.  Minor issue at the moment, but it is confusing.



![Image](https://user-images.githubusercontent.com/56319064/190009046-8bb130c2-969a-4f6e-a074-3bd0ee5c3dc3.jpeg)

**Comment by oliverroick** [comment]
@bwbaker1 Thanks for reviewing this.

Your points 1 and 4 are bugs which I'm addressing right now, PRs will follow shortly. 

To point 2: I can revert the last change and only offer the download for the most recent minor version, the result will look like in the [screenshot I posted](https://github.com/NASA-IMPACT/nasa-apt/issues/527#issuecomment-1232643662) earlier. I just want to make sure the change is really what your users want. Are you certain that they will only want ever download the last minor version?

To points 2/3: We can add/change the helper text, could you send me the preferred wording for this?

**Comment by bwbaker1** [comment]
@oliverroick Thanks for the update.

I discussed point two (only downloading minor version) with Aaron this morning.  He thinks it is preferable for all minor versions to be downloadable.  Sorry I got a little confused while reviewing this.
