### ISSUE TITLE
Use Test MCP Environment

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#547]
## Description

Currently, there is a dev, test, and production environment in MCP. 
We also have a staging environment in UAH.
We currently go from staging in UAH to production in MCP
The goal is to use a test MCP environment as an intermediary between staging in UAH and production in MCP, so that we can push changes into MCP without disturbing live users.

## Acceptance Criteria
- [ ] Deployment pipeline utilizes a test environment in MCP before pushing changes to production

**Comment by aboydnw** [comment]
@wrynearson @oliverroick @naomatheus FYI for potential future development work

**Comment by bwbaker1** [comment]
@wrynearson status of this issue?

**Comment by wrynearson** [comment]
Sorry for my slow reply @bwbaker1. We have not prioritized this – we think that automating the production deployment process is a higher priority, but perhaps we could do the two in tandem.

@sunu @batpad let's look into our deployment pipeline and focus on it for next sprint? cc @leothomas @naomatheus

**Comment by sunu** [comment]
If the goal is to reduce the chances of breakage on production, I don't think adding a new environment will help. Most MCP deployment breakages are due to some sort of misconfiguration. But since configuration is environment specific, adding a new deployment environment is not going to help us reduce the risk of misconfiguration.

I think we should focus on automating the production deployment pipeline instead. Automated deployments will help a lot since that will help us use a consistent deployment pipeline where configuration changes are properly tracked and that will help us avoid misconfiguration

**Comment by wrynearson** [comment]
With https://github.com/NASA-IMPACT/nasa-apt/issues/793, I will close this ticket as not planned.
