### ISSUE TITLE
Resize Images > 6MB

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#587]
### Description
Users are attempting load higher resolution images than originally expected. We would like to ~~increase the file size limit to 15 MB~~ resize images that users upload so that they are less than 6 MB.

**Comment by deborahUAH** [comment]
In addition, the error a user receives in a red box does not last long enough to read (per user feedback). Please increase time of display and let me know what the error says.

**Comment by deborahUAH** [comment]
The sticky error box is a must-have for PI 23.2.

**Comment by wrynearson** [comment]
I will make this a new ticket as the image upload error and quick error message are a different issue than the image size.

**Comment by wrynearson** [comment]
Flagging this for @naomatheus – could you see what the current limit is on prod, and if you can easily change it, please do to 15mb? I assume this is a setting in S3, but it could be a frontend check that we're doing as well (cc @frozenhelium and @batpad)

**Comment by naomatheus** [comment]
Our current file size limitations comes  AWS Lambda and AWS API Gateway - which we use both to host the backend and serve traffic from the frontend client interface, respectively.
AWS Lambda has a current payload limit of 6 MB for synchronous payloads (this cannot be changed). And API GW has a payload limit of 10 MB (This cannot be increased/changed).

Potential solutions:
1. Client-side image resizing: Compress or resize the images on the client-side (in the React application) before uploading them to the backend. This can help ensure that the image size stays within the Lambda and API Gateway limits.

2. Using Amazon S3 for file uploads: Instead of uploading the images directly to Lambda, we upload them to an Amazon S3 bucket. This would require generating a pre-signed URL for the S3 bucket in the backend and sending it to the frontend. The frontend uses this pre-signed URL to upload the image directly to S3. Once the image is in S3, you can use a Lambda function to process it further as needed.

**I recommend option 1.** Solution 2 could create other issues when we need to serve large images. We may encounter limitations with _outbound_ payload size limitations - for re-display and for PDF generation - just as we're now discussing _inbound_ file size limitations.

**Comment by wrynearson** [comment]
Thanks @naomatheus for investigating this and for the write-up of potential solutions.

@deborahUAH I would like to understand the scale of the user need here.
1. Is this something that users have repeatedly requested and flagged as a blocker for them, or is this something that was just mentioned once or twice?
2. Is the need to have high resolution images _stored and displayed_ in APT, or just to not be blocked in the image uploading process (i.e., lower-resolution images can be viewed and downloaded).

Having high resolution images stored, displayed and included in the PDF generation can have many negative consequences, including slow document rendering in the `view` and `edit` modes, slow PDF generation and download in the `PDF` modes, etc.

If these images are being generated by the scientists themselves, I would suggest that it's fair to expect them to upload smaller images.We could let them know in the image upload or warning message that image sizes are limited to a certain size (6 MB).

If we do deem this to be an important issue (scientists bringing their large images and us downsizing them), then we'd need more information on which elements of the image are most important to them – resolution or quality.

cc @batpad @frozenhelium

**Comment by deborahUAH** [comment]
@wrynearson   @bwbaker1 Scientific users can create fairly complicated images which can be quite large. The image could be downsized without too much loss of quality.  We could try choice (1) or  just alter the APT interface to inform the user of the upload size limit and require them to ensure their image is within that limit.  Given resource limitations in Q3, I suggest the later.  Clearly put size limits where uses upload images.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH ^ If it is a simple add on, it would be nice to have a sticky error box stating that a file is too large to upload.

**Comment by wrynearson** [comment]
Thanks @deborahUAH and @bwbaker1 – we can discuss this more on Monday when we scope out features and priorities for the upcoming quarter.

**Comment by wrynearson** [comment]
@batpad let's discuss our options on this ticket when we have the chance.

**Comment by wrynearson** [comment]
@bwbaker1 we've added image resizing functionality. If images are too large, we resize them down. If you or users have any negative feedback about the quality of the images, please let us know and we can adjust the parameters. This is on staging and is ready for testing.

**Comment by bwbaker1** [comment]
@wrynearson I did a couple of tests and didn't notice any quality issues. I suggest we push it to prod and just keep an eye on user feedback.
