### ISSUE TITLE
Bug: Threads.Notify undefined column

### ISSUE THREAD

**Issue by naomatheus** [NASA-IMPACT/nasa-apt#697]
### Summary:
There's an issue in the front-end of the APT application, preventing comments from loading and being edited. It appears that the migration for these columns may have been deployed and then reverted in the same commit. The related migration files can be found here:
- [Migration Deployment](https://github.com/NASA-IMPACT/nasa-apt/blob/develop/db/deploy/threads_notify.sql)
- [Migration Revert](https://github.com/NASA-IMPACT/nasa-apt/blob/develop/db/revert/threads_notify.sql)

### Potential Solution:
To investigate and resolve this issue, perform the following steps:

1. Run the migration on the staging site to verify that the migration works as expected and does not cause any unintended side effects.
2. Once the migration has been successfully tested on the staging site, apply the migration to the MCP deployment instance.
3. Test the comment loading and editing functionality in the APT application to ensure that the issue has been resolved.

After these steps, the comments should load and be editable as expected in the APT application.

**Comment by naomatheus** [comment]
## Sqitch notes (may be outdated)

### Note - `sqitch` binary is located in the repository under `/db/sqitch` reference the sqitch binary in the below commands instead of as a shell path executable. i.e. `./sqitch [command]`

#### 1. View past migrations:

To see the list of past migrations and their current status, use the `sqitch log` command:


#### 2. Test the migration on the staging site:

To test the migration on the staging site, first, ensure that you have the latest version of the codebase and then deploy the migration using the `sqitch deploy` command:


After running the migration, verify that the migration works as expected and does not cause any unintended side effects.

#### 3. Apply the migration to the MCP deployment instance:

If the migration works as expected on the staging site, apply it to the MCP deployment instance using the `sqitch deploy` command:


#### 4. Test the comment loading and editing functionality:

After applying the migration, test the comment loading and editing functionality in the APT application to ensure that the issue has been resolved.

#### 5. Rollback the migration (if necessary):

In case the migration causes any issues or you need to roll it back for any reason, use the `sqitch revert` command:

Replace `TARGET_NAME` with the appropriate target name

**Comment by naomatheus** [comment]
I'll go through these steps on the MCP instance to set up comms with the DB in MCP.

https://sqitch.org/docs/manual/sqitchtutorial/

**Comment by sunu** [comment]
To fix the immediate issue, we should run the latest migrations against the production db. I think the `db/sqitch` bash script documented above is outdated. But I'm fairly sure we can just use the `sqitch` command shipped with ubuntu like we do in the [setup script](https://github.com/NASA-IMPACT/nasa-apt/blob/bbca71b50a8937b8d6713c307c0159a05b266161/fixture_data/setup.sh#L315).

For a long term fix, we should make sure that the migrations run automatically during deployment. But since our RDS databases can be accessed from whitelisted IP addresses only, I can see 2 options:

1. We can whitelist the ip address range used by github actions (for automated deployments through the ci) and the ip of our jumpbox (for manual deployments) and include the sqitch migration command in the ci and deployment script.
2. Or we can add a [lambda backed custom resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources-lambda.html) to the CDK deployment script that will run the migrations inside a lambda during `cdk deploy`

**Comment by leothomas** [comment]
Hey there! 
In regards to the `sqitch` executable in the `db/` folder:  Another option would be to use the [sqitch docker image](https://hub.docker.com/r/sqitch/sqitch/) with a custom command to specify the location of the database against which to run the migrations, that way you can use the same docker container to boostrap the locally running running API using `docker-compose` or use the container as a standalone tool to run the migrations in any of the deployed stacks. 

In regards to running the migrations during deployment: I had opened issue #452 but never got around to it. The list of IP addresses used by Github CI can be found [in the github API's /meta endpoint](https://api.github.com/meta) (under `actions`). I had a discussion with MCP folk about opening the VPC to a specific set of IPs and I think the weren't too keen on it due to the huge number of IPs in the list. I would definitely recommend the lambda backed custom resource route - it's very much a solved problem, @edkeeble has even published a [CDK construct](https://github.com/developmentseed/cdk-bootstrapped-db) for it!

**Comment by sunu** [comment]
Thanks @leothomas! That's super helpful! I think it's totally understandable that MCP admins are hesitant to add too many ips to the whitelist. I'll go ahead and implement option 2 (a lambda backed custom resource to run migrations automatically)

**Comment by naomatheus** [comment]
Checking to see if this is ready to close @sunu

**Comment by sunu** [comment]
Yea @naomatheus, it's safe to close now. I'll handle the long term fix in https://github.com/NASA-IMPACT/nasa-apt/issues/452.
