### ISSUE TITLE
Ensure proper permissions for reviewer metadata

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#761]
_See https://github.com/NASA-IMPACT/nasa-apt/issues/753#issuecomment-1600820097 and previous comments for more details_

## Desired Behavior

- [ ] Reviewer contact information from https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/514 should only be visible to authors and curators in the _edit_ mode, not the _view_ or _PDF exports_

**Comment by bwbaker1** [comment]
@wrynearson My thinking was that the reviewer information would show up in "Viewing" mode. Apparently I missed this ticket since the description is very clear. 

For documents created within the apt environment, the reviewer information does show up in viewing mode. This is not true for uploaded atbds. I'm fine with it only showing up "Editing" mode because we just need the information to reach out to the reviewers. However, I'd prefer to add it to the viewing mode of pdf uploads if there is a simple solution. The reason I would prefer it in viewing mode is that ideally the curator would not open someone's document in editing mode. 

It's okay if the public can see this info on the HTML page. 


Example: I'm in viewing mode and the reviewer information is visible. 
![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/72db2f11-aef7-431a-b8f9-ae07baf8d131)

**Comment by wrynearson** [comment]
Thanks for the explanation @bwbaker1. @frozenhelium could you look into this (adding the reviewer information to the PDF view mode)?
