### ISSUE TITLE
Update Quick Start guide to include instructions regarding MFA/NASA machines

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#782]
### **Description**
MFA is causing a problem for some of our NASA users. Essentially, they cannot download authentication software on NASA machines (that we are aware of). Issue number 2 is that do not have cell service in their buildings, so they can not use an authentication application on their phones. This is user feedback from three people.

### **Acceptance Criteria**
- [ ] Update the quick start guide regarding this issue - perhaps offer a workaround if we think of one

**Comment by wrynearson** [comment]
@bwbaker1 The authentication software shouldn't need cell phone coverage to work, because we're not sending codes via SMS. The MFA tools should work fine with no internet coverage, at least for a limited amount of time. Users will need internet coverage to set up the MFA tool & MFA with APT the first time they use it.

Are password management tools with MFA functionality supported by NASA? One example is [1password](https://1password.com/), which supports MFA, which is installed on the computer.

**Comment by bwbaker1** [comment]
@wrynearson Two recent users are having this issue. They are both using NASA laptops. One specific user is a foreign national, so he doesn't have elevated privileges to download non-NASA approved software. I will check if 1password is an option for them.

 In the meantime, I mentioned the option of downloading and completing a ATBD template, and then we could get it uploaded for them if needed. They seemed okay with that option.

**Comment by wrynearson** [comment]
Could the user take a picture of QR setup code and walk outside so they'd have cell coverage, set up the authenticator, then come back?
