### ISSUE TITLE
No parentheses should enclose a reference if it is at the beginning of a sentence

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#785]
From #781 

> There should not be a parenthesis when a sentence begins a reference.

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/5ae512ce-14da-4787-aaf6-59ed3453ebb6)

## AC

- [ ] No parentheses should enclose a reference if it is at the beginning of a sentence

**Comment by wrynearson** [comment]
@kamicut, if this is difficult, could you scope out the LoE earlier in the sprint?

**Comment by bwbaker1** [comment]
@wrynearson We identified three types of potential cases of adding reference(s).

1. At the beginning of a sentence, which has a different format. Note there may or may not be a comma following the reference. Examples:
According to the American Psychological Association (2000), .....
Doe (2009) states that .....

2. Somewhere in the middle of the sentence. Note there is **no punctuation** following the reference and the reference gets parenthesis. Multiple citations would get one set of parenthesis. Example:
However, a parallel study (Berndt, 1981; Doe, 2002) resulted in ......

3. At the end of a sentence, which is followed by a period. Example:
This is a test sentence (Berndt, 1981; Doe, 2002; Johnson et al., 2001).

**Comment by kamicut** [comment]
There are multiple ways we can tackle this ticket as well as #784:

In order of difficulty (in my opinion, but I differ to @frozenhelium on frontend difficulty)
1. Remove parentheses by default, and have them be written in manually in the editor around the citation by the user
2. Create a fixed ruleset for citations so that formatting & merging of the citations could follow the ruleset (example, no parentheses when starting a line, two citations next to each other should merge, etc.)
3. Create a "citation display editor" component upon inserting a reference, that will allow the editor to display how a citation will look like before it's inserted into the text box.

These have varying degrees of complexity and flexibility. (1) and (3) require some manual work on the side of the user, but are a little bit more flexible. (2) would be less flexible.

**Comment by wrynearson** [comment]
Thanks @kamicut for the summary! I think historically (before any of the DS members current working on the project joined), the idea was to value flexibility and to give the responsibility of sorting the specific details and edge cases to the user. It's a very deep rabbit hole to try to account for all of the different use cases required by users, and citations/references seem to be a pain point for users.

**Comment by wrynearson** [comment]
@bwbaker1 we're going to meet next week and deep-dive into the AGU citation rules to help us decide how to move forward with this, because this is more than just a question about parentheses

**Comment by bwbaker1** [comment]
@wrynearson I discussed the issues related to in-text citations with Aaron. 

1. We agree that the best solution is to do nothing for this use case. Hopefully, this will encourage user(s) to rephrase their sentences and place the citations at the end. Citations at the beginning of a sentence are less common anyways.

We can reassess this after the one-year maintenance period based on user feedback.
