### ISSUE TITLE
Input and output variable tables should be one table

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#849]
### Description
Currently, the input and output variables are all in individual tables. However, this is not ideal especially when there are lots of variables. 

Current Table

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/eb3ce7fa-db3e-4684-9237-f68cd11a7a6d)

The Ideal Table

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/1b37953e-fd59-4653-8e43-115adaab362b)

### Steps
- Determine how to put all the input variables in one table and all the output variables in a single, separate table
- Implement this change
- Test to ensure the tables are working correctly

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review on staging

![image](https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/d460db48-adb6-46e6-af7a-a939c1057756)

**Comment by bwbaker1** [comment]
@wrynearson I'm confused because I'm not seeing a change in the tables. I did a hard refresh and tried multiple browsers. I added you to my test [document](https://nasa-apt.surge.sh/documents/table-test/v1.0).

**Comment by wrynearson** [comment]
Hmm, it looks like the [staging site](https://nasa-apt.surge.sh/) hasn't been updated since March. I admit that I only tested https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/584 locally and assumed it would deploy correctly to staging once it was merged.

@vgeorge it looks like [the action](https://github.com/NASA-IMPACT/nasa-apt-frontend/actions/runs/9599216190) was successful? Could you have a look?

**Comment by vgeorge** [comment]
@bwbaker1 @wrynearson The staging website now has the latest changes on the develop branch. It seems there was a caching issue in the deployment workflow, which should be resolved now. The tables don't appear in the download PDF yet because we need a new backend deploy, but the [PDF preview](https://nasa-apt.surge.sh/documents/table-test/v1.0/pdf-preview) should display the new formatting.

**Comment by bwbaker1** [comment]
@wrynearson @vgeorge This looks great in view mode.

**Comment by wrynearson** [comment]
@vgeorge @sunu @kamicut once we get the PDF exports to work properly, we can mark this as ready for production deployment.

**Comment by wrynearson** [comment]
@bwbaker1 this should be good to go to production, but we're running into issues with the web provider we're using for staging (surge.sh).

If this isn't urgent, I'd suggest waiting until we finish other work and deploy to production later.

**Comment by bwbaker1** [comment]
@wrynearson We can wait and deploy everything at once. Let me know when the table fix for the PDFs is on staging and I will test it (I currently only see the fix in HTML).

**Comment by wrynearson** [comment]
Thanks @bwbaker1. Our work on the PDF aspects of this ticket is ready, but this can't be tested on staging until the caching issue from surge.sh is resolved, which is out of our control. This _should_ all work on production, but to be safe and to be able to thoroughly test on staging, we can wait.

**Comment by sunu** [comment]
@wrynearson I just checked back to see if the surge.sh caching issue is resolved but it's not 😞 I still see the old version
![image](https://github.com/user-attachments/assets/ac4ead9a-1fb2-4dd4-95ab-5cba0fe2159b)

The caching issue hasn't been fixed for weeks and it looks like surge.sh is on its deathbed. I would suggest we move off surge and deploy staging frontend into AWS s3 + cloudfront.

**Comment by wrynearson** [comment]
Thanks @sunu, crazy... Could you open a ticket briefly outlining what that move would entail?

**Comment by sunu** [comment]
> Could you open a ticket briefly outlining what that move would entail?

@wrynearson - I've created an issue for the move: https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/588
