### ISSUE TITLE
Adding PDF versions of Historical ATBDs to the repository

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#884]
### Description
The NASA Earth Observing System (EOS) science project website is migrating to the NASA Science Mission Directorate. The EOS team plans to migrate their historical ATBDs to APT, totaling over 100 historical ATBDs.

We intend to treat these as external ATBD templates, uploading each individual PDF and including available metadata (likely just ATBD identifying information and science keywords). I have the following questions:

1. Does it make sense to structure the repository into two directories - one for standardized ATBDs created with APT and one for historical ATBDs (see diagram)?

![Image](https://github.com/user-attachments/assets/c4142084-b533-4220-a3f6-c1e16ffd0587)

2. The search functionality can simultaneously query both the Standardized_ATBDs and Historical_ATBDs directories, returning comprehensive results from across all available ATBD documents. Will this require a complicated solution?

3. What is the estimated LOE and amount of time to complete both 1 and 2?

This is not finalized yet, but IMPACT management has asked me to draft a plan outlining the estimated LOE, team resources, and the likely duration for both updating the repository and for the team to upload all the PDFs.

**Comment by bwbaker1** [comment]
@sunu @kamicut Will one or both please respond to these questions? I just need general answers at this point to include in the write-up. 

Also, feel free to propose a better solution.

**Comment by kamicut** [comment]
Hey @bwbaker1, this design seems sensible to me. Will inputting the historical ATBD be a manual process (individually, one atbd at a time) or a batch process where we process the PDFs and metadata files in one go? I don't see an issue with search or uploading since it's a small amount of historical ATBDs.

**Comment by bwbaker1** [comment]
Thanks @kamicut! Unfortunately, this will be a manual process to add individual PDFs. 

Will you provide me an estimate how many sprints it would take to make these changes to the repository? Also, how many people from DevSeed would be needed for this?

**Comment by wrynearson** [comment]
1. I think that's more of a question for you, from the discoverability aspect of ATBDs. If the focus is "here are all the ATBDs", then it wouldn't make sense to separate them. But if users want to see only "standard" ATBDs, then it could. I'd think users wouldn't need to make this distinction, but I could be wrong.
2. This is simple if we keep the current upload ATBD format, because we search on the supplemental info (summary, title).

If we do need to distinguish ATBDs based on their structure (instead of their format), we can add a checkbox in the ATBD upload process to indicate that it's an historical ATBD not based on a template, or indicate that it's from a template. We already have the design & language for this, because we say "Upload existing ATBD PDF" in the create ATBD workflow.

<img width="827" alt="image" src="https://github.com/user-attachments/assets/952aaa9f-8540-4698-bf8f-559da7260791">

If we add a checkbox/dropdown to flag the difference between historical and template-based uploads, it will take us about 1 sprint. If we need to re-think how we visually separate these, then it will take more sprints.

**Comment by bwbaker1** [comment]
@wrynearson Ok, I will pitch both ideas when I send the documentation to Rahul.
